language: python
python:
  - "3.9"

before_script:
  - pip install -r requirements.txt
  - python manage.py makemigrations
  - python manage.py migrate

env: DJANGO_SETTINGS_MODULE="nutella.settings"

services:
  - postgresql
  - docker

# command to run tests
script:
  - pytest