language: python
python:
  - "3.6"      # current default Python on Travis CI

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="nutella.settings"

services:
  - postgresql
  - docker

# command to run tests
script:
  - ./manage.py test