# Generated by Django 3.2.7 on 2022-05-27 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutella', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='nutella.category'),
            preserve_default=False,
        ),
    ]
